# Generated by Django 5.0.6 on 2024-08-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
