# Generated by Django 5.0.6 on 2024-08-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_delivery_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_datetime',
        ),
    ]
