# Generated by Django 5.0.6 on 2024-08-06 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_order_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 6, 11, 20, 49, 211525, tzinfo=datetime.timezone.utc
                ),
                help_text="Date and time of delivery",
            ),
        ),
    ]
