# Generated by Django 5.0.6 on 2024-08-06 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_order_delivery_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Date and time of delivery"
            ),
        ),
    ]
